# Generated by Django 6.1.1 on 2026-10-05 01:50

import json

from django.db import migrations, models


def convert_snapshots(apps, schema_editor):
    Order = apps.get_model("orders", "Order")

    for order in Order.objects.all():
        raw = order.shipping_address_snapshot or ""
        lines = [line.strip() for line in str(raw).split("\n") if line.strip()]

        # format: label, street lines (1+), city, postal code, state, country
        if len(lines) >= 6:
            street = lines[1:-4]
            data = {
                "label": lines[0],
                "line1": street[0],
                "line2": ", ".join(street[1:]),
                "city": lines[-4],
                "postal_code": lines[-3],
                "state": lines[-2],
                "country": lines[-1],
            }
        else:
            data = {}

        order.shipping_address_snapshot = json.dumps(data)
        order.save(update_fields=["shipping_address_snapshot"])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_discount_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.RunPython(convert_snapshots, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='shipping_address_snapshot',
            field=models.JSONField(),
        ),
    ]