# Generated by Django 6.1.1 on 2026-10-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_cancel_reason_order_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreturn',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='restock',
            field=models.BooleanField(default=True, help_text='Item wapas bechne layak hai to stock mein add hoga. Damaged ho to uncheck karo.'),
        ),
    ]
