# Generated by Django 6.1.1 on 2026-10-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderreturn_rejection_reason_orderreturn_restock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreturn',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('picked_up', 'Picked up'), ('received', 'Received'), ('refunded', 'Refunded')], default='requested', max_length=20),
        ),
    ]
