# Generated by Django 6.1.1 on 2026-09-28 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default={'home'}, max_length=10)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.city')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addressess', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
