# Generated by Django 6.1.1 on 2026-09-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_tag_slug_alter_category_name_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
